name: Hello-World CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # =======================
  # Frontend Build (Angular)
  # =======================
  frontend_build:
    runs-on: ubuntu-latest
    outputs:
      dist-folder: static
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Angular CLI and dependencies
        run: |
          cd HelloWorldFrontend
          npm install -g @angular/cli@14.0.0
          npm ci

      - name: Build Angular frontend
        run: |
          cd HelloWorldFrontend
          ng build --configuration production
          ls -R static

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
           name: frontend-dist
           path: HelloWorldFrontend/static

  # =======================
  # Backend Build (Java)
  # =======================
  backend_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 18
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 18

      - name: Build backend JAR
        run: |
          cd HelloWorldBackend
          ./mvnw clean package

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: HelloWorldBackend/target/*.jar

  # =======================
  # Backend Test (Java)
  # =======================
  backend_test:
    runs-on: ubuntu-latest
    needs: backend_build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: backend-jar

      - name: Setup Java 18
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 18

      - name: Run backend tests
        run: |
          cd HelloWorldBackend
          ./mvnw test

  # =======================
  # Deploy (Frontend + Backend)
  # =======================
  deploy:
    runs-on: ubuntu-latest
    needs: [frontend_build, backend_build]
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend-dist

      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: backend-jar

      - name: Deploy frontend
        run: |
          sudo mkdir -p /var/www/helloworld/frontend
          sudo cp -r frontend-dist/* /var/www/helloworld/frontend/

      - name: Deploy backend
        run: |
          sudo mkdir -p /var/www/helloworld/backend
          sudo cp backend-jar/*.jar /var/www/helloworld/backend/app.jar

      - name: Restart backend
        run: |
          pkill -f 'java -jar' || true
          nohup java -jar /var/www/helloworld/backend/app.jar > /var/www/helloworld/backend/app.log 2>&1 &
